---
title: "Assignment 1: Introduction to Data Exploration"
author: "Kassie Karnow"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Exploration. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer:
I have a lot of experience using Excel formally and informally. I've done one project for undergrad using R, but it was very basic. I completed a "python bootcamp" for a summer internship project. I have zero experience with Git

2. Are there any components of the course about which you feel confident?

> Answer:
I do not feel overly confident on any aspect. I feel somewhat confident about the reverse learning style because I have done it previously.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I feel a bit apprehensive about being able to balance workload since I do not have a personal laptop I could use; I will have to figure out best times to use computers on campus.


## 2) GitHub

Go over Tasks 1.1. through 1.6 on Course Setup page. Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/kkrocks03/EDE_R_Lab_F26

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
